version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: puller
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    container_name: liquibase
    restart: on-failure
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/puller?serverTimezone=UTC
      - --username=user
      - --password=secret
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data
    networks:
      - backend

  telegram:
    container_name: telegram
    image: cryptan_bot:latest
    ports:
      - "8090:8090"
    depends_on:
      - puller
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - BASEURL_PULLER=http://puller
    networks:
      - backend

  puller:
    container_name: puller
    image: puller:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/puller
    networks:
      - backend


volumes:
  postgres-data:
  rabbitmq-data:

networks:
  backend:
    driver: bridge
